language: python

python:
  - '3.7'
  - '3.6'

branches:
  only:
    - master
    - dev
    - "/^v\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"

install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION gdal scipy numpy
    shapely netCDF4 h5py pytest
  - conda activate test-environment
  - pip install -U pip
  - pip install thyme
  - python setup.py install

script:
- echo "No tests"

deploy:
  provider: pypi
  user: __token__
  password:
    secure: r4d+Vb5cgjEjL+9GtEUHDr0/jSG113QZMXyhNpWu7ZDVHzIRojkk05sM9A6GC5G9W8vvLBNRuhh4DuY2lwcARcAPX4xMmECj1dXRM3YWmoZS8yS8uPr25CGkeMpqoqVcCA8g4nNS5qYogXhN9W91JpEuk10U8sXkx8rJLRu2C1DmhilKNLCo3Z8tMzVTj1i1WhUpRbM++47eXc7LRJq5bl9W55+4mPJ//pZZoy3uh7WIEznHk2dOtl8TOdqDBhivFDerTcGbEvNBY3dfNm0DR8U3uYpLSQImBnDHztq+X7CtScdgpjLL64Tce/JN4I79k8tOgGOO/UMO122ZvT09ETIwV3qUCkJTEi7ZAPg7KfIQhlL4tTGT/7mVbTMxJfsggXQTuiRQMFeoDtjR3VzebEjUZAAInTePeBB1CYxOdYBEHqW7tKHujdXnBgOHDPCbtUfSo1064mQpoxjZwEQNnUit2rkuoSb85XcVYddOloID7stdfX4lMaZ/r3yNJ8xHX0O89JtYC7GFTV11UD+IaLyDw8Flhz2T2U4dUwpSd/EbeDPve3212V5+VMIw55Pvdiip+Xun9oVnk5f+l8D33chSJYhfBSFo7EjppV/dXRdwevmJ87nAk5rGfb7gYIpa2fg+kaJjjy9ElJcUgfIavUVlmFOcB+cfvczKOlItXKw=
  on:
    tags: true
  skip_cleanup: true
  skip_existing: true
